### ISSUE TITLE
OAuth 2 error

### ISSUE THREAD

**Issue by supratim1234567** [twitterdev/twitter-api-java-sdk#11]
Using createTweet method that requires OAuth.
As per the example TwitterCredentialsBearer credentials = new TwitterCredentialsBearer(System.getenv("TWITTER_BEARER_TOKEN")); is giving 401 error so tried creating OAuth 2 credential using
    TwitterCredentialsOAuth2 credentials = new TwitterCredentialsOAuth2(System.getenv("TWITTER_OAUTH2_CLIENT_ID"),
          System.getenv("TWITTER_OAUTH2_CLIENT_SECRET"),
          System.getenv("TWITTER_OAUTH2_ACCESS_TOKEN"),
          System.getenv("TWITTER_OAUTH2_REFRESH_TOKEN"));

Used the credentials in developer's portal 
OAuth 2.0 Client ID and Client Secret

Access Token used 
Generated May 9, 2022
For @<id>
Created with [Read and Write](https://developer.twitter.com/en/docs/apps/app-permissions) permissions

I have elevated access. However getting the error
Authenticating with OAuth 2.0 Application-Only is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].

**Comment by zacmos** [comment]
Thank you for your comment, I'll update the documentation.

`createTweet` can be called using OAuth2 or OAuth1, the SDK does not support OAuth1.
Please make sure that you are not using the OAuth1 parameters, use the OAuth2 ClientId and Client Secret to generate the accessToken and refreshToken. 
You can generate it using Postman or the example https://github.com/twitterdev/twitter-api-java-sdk/blob/main/examples/src/main/java/com/twitter/clientlib/auth/OAuth20GetAccessToken.java.
Please make sure that you are defining the right Scope `tweet.read tweet.write users.read offline.access` 
Once you have your access and refresh token try again


https://api.twitter.com/2/openapi.json#:~:text=post%22%20%3A%20%7B%0A%20%20%20%20%20%20%20%20%22security%22%20%3A%20%5B%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22UserToken%22%20%3A%20%5B%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%20%7B-,%22OAuth2UserToken%22%20%3A%20%5B%20%22users.read%22%2C%20%22tweet.read%22%2C%20%22tweet.write%22%20%5D,-%7D%20%5D%2C%0A%20%20%20%20%20%20%20%20%22tags%22%20%3A%20%5B%20%22Tweets%22%20%5D%2C%0A%20%20%20%20%20%20%20%20%22summary

**Comment by supratim1234567** [comment]
Thanks much for your response, this worked.
