### ISSUE TITLE
Deserialization of TweetSearchResponse throws an NPE in an environment where gson conflicts with other deps

### ISSUE THREAD

**Issue by seinecle** [twitterdev/twitter-api-java-sdk#12]
NPE when deserializing `TweetSearchResponse` in a web app environment with many dependencies (not in a simple Java SE environment with few dependencies)

### Expected behavior
Deserializing a json string into a `TweetSearchResponse` object

### Actual behavior
The deserialization throws an NPE

### Steps to reproduce the behavior

Create a `String` example with the text in tyhe attached file, which is the serialization of a `TweetSearchResponse`
[tweetRecentSearch.txt](https://github.com/twitterdev/twitter-api-java-sdk/files/8663244/tweetRecentSearch.txt)

Then do:

`TweetSearchResponse tweetSearchResponse = TweetSearchResponse.fromJson(example);`

In the context of a Java SE app with few dependencies, no exception is thrown.
The pom.xml of this simple app: 
https://github.com/seinecle/nocodefunctions-as-api/blob/master/pom.xml

In the context of a web app with possibly conflicting dependencies (Google librairies relying on GSON as well), an NPE is thrown. The pom.xml of this bigger app:
https://github.com/seinecle/nocodefunctions/blob/master/pom.xml

### Proposed solution

Do not rely on the `TweetSearchResponse.fromJson()` method and use the Json Binding API instead:

dependencies: https://javaee.github.io/jsonb-spec/users-guide.html

code:

```
Jsonb jsonb = JsonbBuilder.create();
TweetSearchResponse tweetSearchResponse = jsonb.fromJson(example, TweetSearchResponse.class);

```

### Broader suggestion
It could be interesting to drop the dependency on gson and rely on a more conventional json-b API and implementation:

https://javaee.github.io/jsonb-spec/index.html

**Comment by zacmos** [comment]
Hi,
I understand the problem but didn't manage to re-create it.
Does this link help? 
https://www.baeldung.com/maven-version-collision#:~:text=Excluding%20a%20Transitive%20Dependency%20From%20an%20Artifact

something like
        ```
<dependency>
            <groupId>com.twitter</groupId>
            <artifactId>twitter-api-java-sdk</artifactId>
            <version>1.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.gson</groupId>
                    <artifactId>gson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by seinecle** [comment]
Very clear thank you.
