### ISSUE TITLE
Method to retrieve the embeddable version of tweet?

### ISSUE THREAD

**Issue by seinecle** [twitterdev/twitter-api-java-sdk#15]
I am looking for a method to retrieve the html code that corresponds to a tweet's embeddable version?

For refernce, Twitter4J provides such a set of methods with the `OEmbedRequest` and `OEmbed` classes:

```
                OEmbedRequest oEmbedRequest = new OEmbedRequest(Long.valueOf(tweet.getId()), "");
                oEmbedRequest.setMaxWidth(550);
                oEmbedRequest.setOmitScript(true);
                twitter = TwitterFactory.getInstance();

                OEmbed embed = twitter.getOEmbed(oEmbedRequest);
                String tweetAsHtml = embed.getHtml();

```
https://twitter4j.org/oldjavadocs/3.0.2/twitter4j/OEmbedRequest.html

Thank you.

**Comment by zacmos** [comment]
Hi, 
As far as I see Twitter4J uses the V1 APIs, `restBaseURL` is https://api.twitter.com/1.1/
At the moment this functionality is not supported by V2 APIs.

**Comment by seinecle** [comment]
Thank you
