### ISSUE TITLE
"Unable to give access to the App" when following steps from example

### ISSUE THREAD

**Issue by seinecle** [twitterdev/twitter-api-java-sdk#17]
Trying to authenticate a user of the app with `TwitterOAuth20Service`. The auth url returns "Unable to give access to the App"

### Expected behavior
The auth url should present the user with the choice to authorize the app.

### Actual behavior
![image](https://user-images.githubusercontent.com/1244100/168348170-6aee0e15-33c2-4b59-a22f-14ebb8438f35.png)

### Steps to reproduce the behavior
These are the steps I follow, directly taken from [the code example](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/examples/src/main/java/com/twitter/clientlib/auth/OAuth20GetAccessToken.java). A screenshot just below shows where I take the tokens from. I suspect I do something silly here, your advice is welcome.

```
        Properties props = new Properties();
        props.load(new FileInputStream("private/props.properties"));

        TwitterCredentialsOAuth2 credentials = new TwitterCredentialsOAuth2(
                props.getProperty("twitter_client_id"), // see A in the screenshot
                props.getProperty("twitter_client_secret"),  // see B in the screenshot
                props.getProperty("twitter_access_token"), // see C in the screenshot
                System.getenv("TWITTER_OAUTH2_REFRESH_TOKEN") // I don't see such a refresh token in the dev console ??
                );

        TwitterOAuth20Service service = new TwitterOAuth20Service(
                credentials.getTwitterOauth2ClientId(),
                credentials.getTwitterOAuth2ClientSecret(),
                "http://twitter.com",
                "offline.access tweet.read");

        OAuth2AccessToken accessToken = null;
        try {
            final Scanner in = new Scanner(System.in, "UTF-8");
            System.out.println("Fetching the Authorization URL...");

            final String secretState = "state";
            PKCE pkce = new PKCE();
            pkce.setCodeChallenge("challenge");
            pkce.setCodeChallengeMethod(PKCECodeChallengeMethod.PLAIN);
            pkce.setCodeVerifier("challenge");
            String authorizationUrl = service.getAuthorizationUrl(pkce, secretState);

            System.out.println("Go to the Authorization URL and authorize your App:\n"
                    + authorizationUrl + "\nAfter that paste the authorization code here\n>>");

          // at this step, I copy paste the URL in a browser and this is where the error msg is returned

            final String code = in.nextLine();
            System.out.println("\nTrading the Authorization Code for an Access Token...");
            accessToken = service.getAccessToken(pkce, code);

            System.out.println("Access token: " + accessToken.getAccessToken());
            System.out.println("Refresh token: " + accessToken.getRefreshToken());
        } catch (Exception e) {
            System.err.println("Error while getting the access token:\n " + e);
            e.printStackTrace();
        }

```
Screenshot showing where I take the tokens used in the credentials:

![image](https://user-images.githubusercontent.com/1244100/168371198-6318ab71-6205-4b13-a556-5434ce15a733.png)

**Comment by zacmos** [comment]
Hi, 
Few comments to the above flow:
1. When getting the OAuth2 access token, `TwitterCredentialsOAuth2.twitterOAuth2AccessToken` and `TwitterCredentialsOAuth2.twitterOAuth2RefreshToken`  should be empty or null. The access token that you used is not relevant for this flow.
2. In the example code, `getAccessToken()`, setting the scope should be 
 ```
 credentials.getTwitterOAuth2ClientSecret(),
        "http://twitter.com",
        "offline.access tweet.read users.read");
```
 I'll update it.

Not sure why you got the "Something went wrong" error, do you have your proj/app "User authentication settings" turned on? (Setup the OAuth2.0)..
What happens if you are trying to get the OAuth2 access&refresh token using Postman?

**Comment by seinecle** [comment]
Thank you for your response. I have replaced the token secret and the refresh token by empty Strings.

Next, I was curious about the part of the oauth url which showed twitter.com in the `redirect_uri` param. Evidently, this twitter.com redirect url is just a placeholder in the docs. It should be replaced by one of the urls the app designer has added in the settings of the Twitter app on https://dev.twitter.com. Doing it solved my issue. Maybe the docs could be updated for that?

**Comment by kunalbarchha** [comment]
@zacmos Getting 'Something went Wrong' to me too. Only setting client Id and Client Secret in the Credentials. Any fix for this ?
