### ISSUE TITLE
OAuth 1.0a User Context authentication

### ISSUE THREAD

**Issue by LiveXenon** [twitterdev/twitter-api-java-sdk#18]
Is it possible / will it be possible to use this library with OAuth 1.0a User Context in the future?

In the API v2 documentation I read that you can access:

-  OAuth 1.0a User Context
-  OAuth 2.0 App-Only
-  OAuth 2.0 Authorization code with PKCE

**Comment by zacmos** [comment]
Hi, the plan is to reduce and deprecate the use of OAuth1 in V2 APIs, therefore the SDK does not support it.

**Comment by axitasavani** [comment]
Hi, @zacmos  if we want to tweet on behalf of another twitter user then which Outh is used? 
- Bcz Outh1.0 is used for that now it has been deprecated in V2.
