### ISSUE TITLE
 json serialization error

### ISSUE THREAD

**Issue by seinecle** [twitterdev/twitter-api-java-sdk#38]
Error with Json deserialization

### Expected behavior

Json serialization should run fine when fetching tweets

### Actual behavior

A json serialization error occurs. I don't have the corresponding tweet. The trace is:

`javax.json.bind.JsonbException: Internal error: No enum constant com.twitter.clientlib.model.Point.TypeEnum.Point
`  
### Steps to reproduce the behavior
Fetch tweets

**Comment by zacmos** [comment]
Hi, I didn't manage to reproduce this error, it would be interesting to know how did you get it, which tweet was it and what enum value was populated for `Point`..
