### ISSUE TITLE
No url property in media object

### ISSUE THREAD

**Issue by shivam-2701** [twitterdev/twitter-api-java-sdk#39]
One line summary of the issue here.
There is no intuitive way to extract media url from any tweet response.
### Expected behavior
Presence of url property in media object

### Actual behavior
Url of the media object is shown in the text of data property of tweet object

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by rzo1** [comment]
I am using 

```
if (mediaEntity instanceof Video v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;
        }
        if (mediaEntity instanceof Photo v) {
            return v.getUrl() != null ? v.getUrl().toString() : Constants.EMPTY_STRING;
        }
        if (mediaEntity instanceof AnimatedGif v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;
        }
```

with media field Expansion

```
MEDIA_FIELDS.add("duration_ms");
        MEDIA_FIELDS.add("height");
        MEDIA_FIELDS.add("media_key");
        MEDIA_FIELDS.add("preview_image_url");
        MEDIA_FIELDS.add("public_metrics");
        MEDIA_FIELDS.add("width");
        MEDIA_FIELDS.add("url");
```

I agree, that it isn't user friendly to match attachments (media) and media keys to obtain fully hydrated Tweet entities.

Would love to see this on the SDK side.

**Comment by shivam-2701** [comment]
@rzo1 
Thank you Sir, for the reply. 
I have some doubts on how to access mediaEntity from the first code block I am using  Get2TweetsResponse in findTweetsById
method can you please point me to any documentation.
P.S. Thanks for the help

**Comment by rzo1** [comment]
The **expansion** concept is documented [here](https://developer.twitter.com/en/docs/twitter-api/expansions).

You need to tell the SDK, that you want to retrieve expansions as well as media fields, see https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/api/TweetsApi.java#L962

This can be done by something like

```
  final Get2TweetsResponse response =
                        twitterApi.tweets()
                                .findTweetsById(ids)
                                .expansions(TwitterEntityFields.getExpansions())
                                .mediaFields(TwitterEntityFields.getMediaFields())
                                .placeFields(TwitterEntityFields.getPlaceFields())
                                .userFields(TwitterEntityFields.getUserFields())
                                .tweetFields(TwitterEntityFields.getTweetFields())
```

with something like

```
public abstract class TwitterEntityFields {

    private final static Set<String> TWEET_FIELDS = new HashSet<>();
    private final static Set<String> PLACE_FIELDS = new HashSet<>();
    private final static Set<String> MEDIA_FIELDS = new HashSet<>();
    private final static Set<String> USER_FIELDS = new HashSet<>();
    private final static Set<String> EXPANSIONS = new HashSet<>();

    static {
        TWEET_FIELDS.add("author_id");
        TWEET_FIELDS.add("id");
        TWEET_FIELDS.add("created_at");
        TWEET_FIELDS.add("public_metrics");
        TWEET_FIELDS.add("entities");
        TWEET_FIELDS.add("geo");
        TWEET_FIELDS.add("lang");
        TWEET_FIELDS.add("source");
        TWEET_FIELDS.add("referenced_tweets");
        TWEET_FIELDS.add("in_reply_to_user_id");

        PLACE_FIELDS.add("country");
        PLACE_FIELDS.add("geo");
        PLACE_FIELDS.add("name");
        PLACE_FIELDS.add("place_type");
        PLACE_FIELDS.add("contained_within");

        MEDIA_FIELDS.add("duration_ms");
        MEDIA_FIELDS.add("height");
        MEDIA_FIELDS.add("media_key");
        MEDIA_FIELDS.add("preview_image_url");
        MEDIA_FIELDS.add("public_metrics");
        MEDIA_FIELDS.add("width");
        MEDIA_FIELDS.add("url");

        EXPANSIONS.add("author_id");
        EXPANSIONS.add("attachments.media_keys");
        EXPANSIONS.add("geo.place_id");

        USER_FIELDS.add("created_at");
        USER_FIELDS.add("description");
        USER_FIELDS.add("location");
        USER_FIELDS.add("profile_image_url");
        USER_FIELDS.add("protected");
        USER_FIELDS.add("public_metrics");
        USER_FIELDS.add("url");
        USER_FIELDS.add("verified");
    }

    public static Set<String> getTweetFields() {
        return Collections.unmodifiableSet(TWEET_FIELDS);
    }

    public static Set<String> getPlaceFields() {
        return Collections.unmodifiableSet(PLACE_FIELDS);
    }

    public static Set<String> getMediaFields() {
        return Collections.unmodifiableSet(MEDIA_FIELDS);
    }

    public static Set<String> getUserFields() {
        return Collections.unmodifiableSet(USER_FIELDS);
    }

    public static Set<String> getExpansions() {
        return Collections.unmodifiableSet(EXPANSIONS);
    }
}
```
In the `Get2TweetsResponse` , you can use `getIncludes()` to obtain the [expansions](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/model/Expansions.java).

Yo can then retrieve the media objects on the exapnsions object via https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/model/Expansions.java#L117

**Comment by shivam-2701** [comment]
> The **expansion** concept is documented [here](https://developer.twitter.com/en/docs/twitter-api/expansions).
> 
> You need to tell the SDK, that you want to retrieve expansions as well as media fields, see [https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/api/TweetsApi.java#L962](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/api/TweetsApi.java?rgh-link-date=2022-08-01T11%3A26%3A04Z#L962)
> 
> This can be done by something like
> 
> ```
>   final Get2TweetsResponse response =
>                         twitterApi.tweets()
>                                 .findTweetsById(ids)
>                                 .expansions(TwitterEntityFields.getExpansions())
>                                 .mediaFields(TwitterEntityFields.getMediaFields())
>                                 .placeFields(TwitterEntityFields.getPlaceFields())
>                                 .userFields(TwitterEntityFields.getUserFields())
>                                 .tweetFields(TwitterEntityFields.getTweetFields())
> ```
> 
> with something like
> 
> ```
> public abstract class TwitterEntityFields {
> 
>     private final static Set<String> TWEET_FIELDS = new HashSet<>();
>     private final static Set<String> PLACE_FIELDS = new HashSet<>();
>     private final static Set<String> MEDIA_FIELDS = new HashSet<>();
>     private final static Set<String> USER_FIELDS = new HashSet<>();
>     private final static Set<String> EXPANSIONS = new HashSet<>();
> 
>     static {
>         TWEET_FIELDS.add("author_id");
>         TWEET_FIELDS.add("id");
>         TWEET_FIELDS.add("created_at");
>         TWEET_FIELDS.add("public_metrics");
>         TWEET_FIELDS.add("entities");
>         TWEET_FIELDS.add("geo");
>         TWEET_FIELDS.add("lang");
>         TWEET_FIELDS.add("source");
>         TWEET_FIELDS.add("referenced_tweets");
>         TWEET_FIELDS.add("in_reply_to_user_id");
> 
>         PLACE_FIELDS.add("country");
>         PLACE_FIELDS.add("geo");
>         PLACE_FIELDS.add("name");
>         PLACE_FIELDS.add("place_type");
>         PLACE_FIELDS.add("contained_within");
> 
>         MEDIA_FIELDS.add("duration_ms");
>         MEDIA_FIELDS.add("height");
>         MEDIA_FIELDS.add("media_key");
>         MEDIA_FIELDS.add("preview_image_url");
>         MEDIA_FIELDS.add("public_metrics");
>         MEDIA_FIELDS.add("width");
>         MEDIA_FIELDS.add("url");
> 
>         EXPANSIONS.add("author_id");
>         EXPANSIONS.add("attachments.media_keys");
>         EXPANSIONS.add("geo.place_id");
> 
>         USER_FIELDS.add("created_at");
>         USER_FIELDS.add("description");
>         USER_FIELDS.add("location");
>         USER_FIELDS.add("profile_image_url");
>         USER_FIELDS.add("protected");
>         USER_FIELDS.add("public_metrics");
>         USER_FIELDS.add("url");
>         USER_FIELDS.add("verified");
>     }
> 
>     public static Set<String> getTweetFields() {
>         return Collections.unmodifiableSet(TWEET_FIELDS);
>     }
> 
>     public static Set<String> getPlaceFields() {
>         return Collections.unmodifiableSet(PLACE_FIELDS);
>     }
> 
>     public static Set<String> getMediaFields() {
>         return Collections.unmodifiableSet(MEDIA_FIELDS);
>     }
> 
>     public static Set<String> getUserFields() {
>         return Collections.unmodifiableSet(USER_FIELDS);
>     }
> 
>     public static Set<String> getExpansions() {
>         return Collections.unmodifiableSet(EXPANSIONS);
>     }
> }
> ```
> 
> In the `Get2TweetsResponse` , you can use `getIncludes()` to obtain the [expansions](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/model/Expansions.java?rgh-link-date=2022-08-01T11%3A26%3A04Z).
> 
> Yo can then retrieve the media objects on the exapnsions object via [https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/model/Expansions.java#L117](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/model/Expansions.java?rgh-link-date=2022-08-01T11%3A26%3A04Z#L117)

Sir I am aware of the steps mentioned here.
My doubt lies with the use of mediaEntity object and MediaEntityAdapter


     ` if (mediaEntity instanceof Video v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;
        }
        if (mediaEntity instanceof Photo v) {

            return v.getUrl() != null ? v.getUrl().toString() : Constants.EMPTY_STRING;

        }

        if (mediaEntity instanceof AnimatedGif v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;

        }`

Mentioned in this comment

**Comment by rzo1** [comment]
Sorry ;) - `MediaEntityAdapter` is just a custom class / record, which holds a `Media`  - nothing special and not from the SDK. We are doing these abstractions to be able to easily switch the underlying client library (twittered, twitter4j or the official sdk now).

As we are coming from `twitter4j`, we are used to fully hydrated tweets objects. Therefore, we are doing the following to get fully hydrated objects with the official SDK now:

```java
public class TweetAdapter {
    private final Tweet tweet;
    private final Set<SymbolEntityAdapter> symbols = new HashSet<>();
    private final Set<HashtagEntityAdapter> hashtags = new HashSet<>();
    private final Set<UserMentionEntityAdapter> mentions = new HashSet<>();
    private final Set<URLEntityAdapter> urls = new HashSet<>();
    private final Set<MediaEntityAdapter> media = new HashSet<>();
    private final UserAdapter user;
    private final PlaceAdapter place;

    public StatusAdapter(Tweet tweet, Expansions expansions) {
        assert (tweet != null);
        assert (expansions != null);
        this.tweet = tweet;
        collectTextEntities(tweet);
        this.place = collectPlaces(expansions);
        this.media.addAll(collectMedia(expansions));
        this.user = collectUser(expansions);
    }

    private UserAdapter collectUser(Expansions expansions) {
        if (expansions != null && expansions.getUsers() != null) {
            for (User user : expansions.getUsers()) {
                if (user.getId().equals(tweet.getAuthorId())) {
                    return new UserAdapter(user);
                }
            }
        }
        throw new TwitterDataException("Could not extract Tweet's author. Tweet with ID = " + tweet.getId());
    }

    private Set<MediaEntityAdapter> collectMedia(Expansions expansions) {
        final Set<MediaEntityAdapter> result = new HashSet<>();
        if (expansions != null) {
            final TweetAttachments attachments = tweet.getAttachments();
            final List<Media> media = expansions.getMedia();

            if (attachments != null && media != null) {
                if (attachments.getMediaKeys() != null) {
                    for (String mKey : attachments.getMediaKeys()) {
                        for (Media m : media) {
                            if (m.getMediaKey() != null && m.getMediaKey().equals(mKey)) {
                                result.add(new MediaEntityAdapter(m));
                            }
                        }
                    }
                }
            }
        }
        return result;
    }

    private PlaceAdapter collectPlaces(Expansions expansions) {
        if (expansions != null
                && tweet.getGeo() != null
                && expansions.getPlaces() != null) {
            final String placeId = tweet.getGeo().getPlaceId();

            for (Place place : expansions.getPlaces()) {

                if (place.getId().equals(placeId)) {
                    return new PlaceAdapter(place);
                }

            }

        }
        return null;
    }

    private void collectTextEntities(Tweet tweet) {
        final FullTextEntities entities = tweet.getEntities();

        if (entities != null) {
            if (entities.getCashtags() != null) {
                for (CashtagEntity c : entities.getCashtags()) {
                    symbols.add(new SymbolEntityAdapter(c));
                }
            }

            if (entities.getHashtags() != null) {
                for (HashtagEntity c : entities.getHashtags()) {
                    hashtags.add(new HashtagEntityAdapter(c));
                }
            }
            if (entities.getMentions() != null) {
                for (MentionEntity c : entities.getMentions()) {
                    mentions.add(new UserMentionEntityAdapter(c));
                }
            }
            if (entities.getUrls() != null) {
                for (UrlEntity c : entities.getUrls()) {
                    urls.add(new URLEntityAdapter(c));
                }
            }
        }
    }
 
 // getters    
}
```

and

```java
public class MediaEntityAdapter{

    private final Media mediaEntity;

    public MediaEntityAdapter(Media entity) {
        assert (entity != null);
        this.mediaEntity = entity;
    }

    public String getText() {
        if (mediaEntity instanceof Photo v) {
            return v.getAltText() != null ? v.getAltText() : Constants.EMPTY_STRING;
        }
        return Constants.EMPTY_STRING;
    }


    public String getType() {
        return mediaEntity.getType();
    }


    public String getURL() {
        if (mediaEntity instanceof Video v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;
        }
        if (mediaEntity instanceof Photo v) {
            return v.getUrl() != null ? v.getUrl().toString() : Constants.EMPTY_STRING;
        }
        if (mediaEntity instanceof AnimatedGif v) {
            return v.getPreviewImageUrl() != null ? v.getPreviewImageUrl().toString() : Constants.EMPTY_STRING;
        }

        return Constants.EMPTY_STRING;
    }

}

```

**Comment by shivam-2701** [comment]
> ```java
> this.media.addAll(collectMedia(expansions));
>         this.user = collectUser(expansions);
> ```

Thank You Sir for the Help.
