### ISSUE TITLE
RulesResponseMetadata throwing exeption on new field from Twitter

### ISSUE THREAD

**Issue by Roma-Kyrnis** [twitterdev/twitter-api-java-sdk#4]
https://github.com/twitterdev/twitter-api-java-sdk/blob/b06cfc01c7bb886fcbbf5a39cce814c80f5bdc35/src/main/java/com/twitter/clientlib/model/RulesResponseMetadata.java#L165

**Comment by Roma-Kyrnis** [comment]
Can you help to resolve this issue?

Here is scrinshots:
![image](https://user-images.githubusercontent.com/56438694/162813445-2911383e-2c43-4f13-b657-e99eb56ca36f.png)

I'm executing this method:
![image](https://user-images.githubusercontent.com/56438694/162813531-4569b68a-beb1-49f5-8439-c6564d15ce1d.png)

In Postman I've got 200 status with additional field:
![image](https://user-images.githubusercontent.com/56438694/162813677-771c58cd-4aa4-4556-88e3-29b74acf2957.png)

**Comment by zacmos** [comment]
Added the missing field `result_count` to `RulesResponseMetadata`, please use the new version `1.1.3`.

**Comment by Roma-Kyrnis** [comment]
Thank you!
