### ISSUE TITLE
the class UrlFields UrlImage is not the same as the file name UrlImage.java URLFields.java

### ISSUE THREAD

**Issue by LiuQhahah** [twitterdev/twitter-api-java-sdk#40]
the class UrlFields UrlImage is not the same as the file name UrlImage.java URLFields.java

### Expected behavior

When building the code, the result is a failure.

### Steps to reproduce the behavior

twitter-api-java-sdk\src\main\java\com\twitter\clientlib\model\URLImage.java:62:8
java: class UrlImage is public, should be declared in a file named UrlImage.java

**Comment by amacbride** [comment]
The workaround is to rename the following files:

src/main/java/com/twitter/clientlib/model/URLFields.java -> src/main/java/com/twitter/clientlib/model/UrlFields.java
src/main/java/com/twitter/clientlib/model/URLImage.java -> src/main/java/com/twitter/clientlib/model/UrlImage.java

src/test/java/com/twitter/clientlib/model/URLImageTest.java -> src/test/java/com/twitter/clientlib/model/UrlImageTest.java
src/test/java/com/twitter/clientlib/model/URLFieldsTest.java -> src/test/java/com/twitter/clientlib/model/UrlFieldsTest.java

**Comment by zacmos** [comment]
Please check v2.0.3
