### ISSUE TITLE
tweetsIdLikingUsers returns 403

### ISSUE THREAD

**Issue by locked-fg** [twitterdev/twitter-api-java-sdk#42]
Call to ```api.users().tweetsIdLikingUsers("...").execute()``` returns Status Code 403 

### Expected behavior

I would expect that the call returns with a 200.
I checked the API if it should only work with my own tweets but as of my interpretation it should work with any tweet.

### Actual behavior

I initialize the API, test the validity of the object with a call to ```findMyUser()``` (which does not throw an exception).
Then I call 
```
api.users().tweetsIdLikingUsers("1565414244052508673").execute();
```
(Which should list the Users of the tweet https://twitter.com/TwitterDev/status/1565414244052508673 .)
This call results in a ApiException 
```
Response headers:  com.twitter.clientlib.ApiException: Message: 
HTTP response code: 403
HTTP response body: {
  "title": "Forbidden",
  "type": "about:blank",
  "status": 403,
  "detail": "Forbidden"
}
```

### Steps to reproduce the behavior

Just initialize the api and call
```api.users().tweetsIdLikingUsers("1565414244052508673").execute();```

**Comment by zacmos** [comment]
Please check that you can call the API using Postman.
Do you use OAuth 2.0 App-only or OAuth 2.0 Authorization Code with PKCE.
The above "Steps to reproduce" ended successfully when I ran it.

**Comment by locked-fg** [comment]
I assume PKCE (I log in via Callback for my account) and then use this code (simplified to the minimum)
```
public class TestLike {
    public static void main(String[] args) throws ApiException {
        var credentials = new TwitterCredentialsOAuth2(
                "...", "...", "...", "...");
        var api = new TwitterApi(credentials);
        System.out.println(api.users().findMyUser().execute().getData().getId());
        var response1 = api.users().tweetsIdLikingUsers("1565414244052508673").execute(); // returns 403
    }
}
```
(Struggling a bit qith Postman currently - but working on it)

But while reading https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code - might it be that I need to have the scope `like.read | Tweets you’ve liked and likes you can view.` ?

**Comment by zacmos** [comment]
You do need to set the scope, please check the api [link](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users#:~:text=each%20authenticated%20user-,OAuth%202.0,-scopes%20required%20by)
Please also add this scope `offline.access`

**Comment by locked-fg** [comment]
Ah I can confirm: it works given the right scopes.
Sorry for the inconvenience. 
I'm closing it.

**Comment by ericwomer** [comment]
> You do need to set the scope, please check the api [link](https://developer.twitter.com/en/docs/twitter-api/tweets/likes/api-reference/get-tweets-id-liking_users#:~:text=each%20authenticated%20user-,OAuth%202.0,-scopes%20required%20by) Please also add this scope `offline.access`

How do you set the scope?

**Comment by locked-fg** [comment]
https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code
In the code during initialization of ```TwitterOAuth20Service```
