### ISSUE TITLE
Unable to avoid sporadic 429 too many connections on stream 

### ISSUE THREAD

**Issue by mhoshi-vm** [twitterdev/twitter-api-java-sdk#43]
Currently I have a `elevated` account on twitter.
As per my understanding twitter only allows 1 stream connection per 1 app.
As I understand this I am making sure I am not running multiple instances of my app, and of course not sharing the bearer token to anyone else.

However I am unable to make my stream application running stably.
The error starts by suddenly receiving a  `Socket.Exception connection reset` on my stream app.
After that when I start my app I receive a 429 too many connection error. I am making sure my previous connection has been cleaned during shutdown, but there seems to be a connection which I am unable to identify.

I have already tried multiple things which did not participate to help this issue

- Do not use connection pools
- Do not retry on failure (as the retry option seems to be unhelpful on 429 too many connections errors)
- Use HTTP 1.1
- Clean up connection on shutdown

The following is the code fragments.

https://github.com/tanzu-japan/twitter-wordcloud-demo/blob/main/src/main/java/jp/vmware/tanzu/twitterwordclouddemo/utils/TwitterStreamClientImpl.java#L66-L77

https://github.com/tanzu-japan/twitter-wordcloud-demo/blob/main/src/main/java/jp/vmware/tanzu/twitterwordclouddemo/utils/TwitterStreamClientImpl.java#L209-L220

### Expected behavior

Stable and long live stream connections without sudden disconnect

### Actual behavior

Sudden disconnect with 429 too many connection, even with several actions to clean connections on shutdown.

### Steps to reproduce the behavior

Run a stream application with "elevated" account.

**Comment by zacmos** [comment]
Hi @mhoshi-vm, I've tried to run a simple test with similar code to yours, the same way of creation of `TwitterApi`, calling `searchStream` but didn't manage to re-create the 429. 
429 happened to me only when I called the `searchStream` twice.
You can check more about the rate limits [here](https://developer.twitter.com/en/docs/twitter-api/rate-limits) and [here](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections#:~:text=Rate%20limits%20and%20usage)

Isn't there an option that somehow another thread/process executes the same api?

I'll check more about similar cases that happened in the past

**Comment by zacmos** [comment]
@mhoshi-vm , any updates about this issue? 
As far as I checked 429 happened to me only when I called the `searchStream` twice using the same credentials.
Is it possible that  another thread executes the same api? Maybe inside Spring?

**Comment by ibrahimjamil** [comment]
@zacmos many people are facing this issue it's a long-running issue and the twitter team didn't plan to resolve this issue.
