### ISSUE TITLE
Building a bot 

### ISSUE THREAD

**Issue by nn81** [twitterdev/twitter-api-java-sdk#48]
Hello zacmos,

Thank you for sharing this comprehensive library.

Please pardon my ignorance but how would you recommend building a bot for replying/acting everytime that someone @'s its name?

There exists the [streaming API](https://dev.twitter.com/streaming/overview) but how would one use this reacting to being called instead of pooling twitter every few seconds.

Perhaps possible to provide a sample example? Many thanks!!

**Comment by JessicaGarson** [comment]
Hi! 

Thanks for reaching out. For the future, our [community forums](https://twittercommunity.com/) are likely a better place to get support for things like this. There is also a great community [slack channel](https://botmakers.org/)(external to Twitter) that I've used to run ideas by other bot makers the in the past.

 To create a rule, you could use the [filtered stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction) that looks for @mentions and replies with a Tweet using the [manage Tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/introduction) endpoint. You could also use [recent search](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent) in a similar way too.

I have a few examples of bots I've built in Python. I'm a Python developer, but our team is hoping to expand our tutorials to other languages:
- [Creating a Twitter bot](https://developer.twitter.com/en/docs/tutorials/creating-a-twitter-bot-with-python--oauth-2-0--and-v2-of-the-twi)
- [Kickstart your Twitter bot with our Glitch example written in Python](https://developer.twitter.com/en/docs/tutorials/kickstart-your-twitter-bot-with-our-glitch-example-written-in-py)
- [Devs in the Details: How to Create a Twitter Bot](https://www.youtube.com/watch?v=FzvTg6sYnec)

Also, I like [bot wiki for bot examples](https://botwiki.org/resources/twitterbots) and other resources. I hope this helps!

**Comment by nn81** [comment]
Thanks Jessica but unfortunately those resources are too generic.

I'm really looking for a sample in Java language for this usage.
Why not opening on this repository the forum option?

The other forum is large but only has some 50 questions related to java and mostly unanswered.

**Comment by JessicaGarson** [comment]
Thanks for your feedback. I'd like to make a Java example in the future. I've worked with a bot maker in the past [built this template](https://github.com/joesondow/lambda-twitter-base), which could be combined with this SDK for this use. 

Feel free to open up a post on the send me a DM if you don't hear anything. I'll also pass on your suggestions for support in the future.
